### ISSUE TITLE
SQL-Task-Database Migration

### ISSUE THREAD

**Issue by plc-dev** [plc-dev/aladin#18]
The following SQLite DB-dumps have to be converted to PostgresSQL-dumps:

https://drive.google.com/file/d/1IyIT2hAYcTlayuqc2l4Xd-4fDs2UxKpI/view?usp=sharing

**Comment by sjanasek** [comment]
the remaining dumps will follow
https://drive.google.com/drive/folders/1WLHWnwDEQbn-6UDeEe122bvm-TIQhbSu?usp=sharing

**Comment by sjanasek** [comment]
https://drive.google.com/drive/folders/1WLHWnwDEQbn-6UDeEe122bvm-TIQhbSu?usp=sharing

**Comment by sjanasek** [comment]
verwendet:
https://pgloader.io
https://gist.github.com/eclubb/2253099
